const defaultURL = name => window.FINTECH_SAME_ORIGIN ? `${location.origin}/api/${name}` : `${location.protocol}//${location.hostname.includes(':') ? '[' + location.hostname + ']' : location.hostname}:${window.FINTECH_PORTS?.[name] ?? (name === 'book' ? 8010 : 8020)}`;
export const storage = {get(key, fallback) {try {const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback;} catch {return fallback;}}, set(key, value) {try {localStorage.setItem(key, JSON.stringify(value));return true;} catch {return false;}}};
export function baseURL(name) {const key = name === 'book' ? 'AI_BOOKKEEPER_API' : 'AI_TRADER_API'; try {return (localStorage.getItem(key) || defaultURL(name)).replace(/\/$/, '');} catch {return defaultURL(name);}}
export function saveConnections(book, trader) {for (const value of [book, trader]) {const url = new URL(value);if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || url.search || url.hash) throw new Error('请输入不含密码、参数的 HTTP / HTTPS 服务地址');}localStorage.setItem('AI_BOOKKEEPER_API', book.replace(/\/$/, ''));localStorage.setItem('AI_TRADER_API', trader.replace(/\/$/, ''));}
export function resetConnections() {localStorage.removeItem('AI_BOOKKEEPER_API');localStorage.removeItem('AI_TRADER_API');}
export async function request(service, path, {method = 'GET', body, signal, timeout = 15000, headers = {}} = {}) {
 const controller = new AbortController();const abort = () => controller.abort();signal?.addEventListener('abort', abort, {once:true});if(signal?.aborted)controller.abort();const timer = setTimeout(abort, timeout);
 try {const response = await fetch(baseURL(service) + path, {method, body: body instanceof FormData ? body : body === undefined ? undefined : JSON.stringify(body), headers: {...(body && !(body instanceof FormData) ? {'Content-Type':'application/json'} : {}), ...headers}, credentials:'same-origin', signal:controller.signal});const data = await response.json().catch(() => ({}));if (!response.ok) {const detail = data.detail;const error=new Error(typeof detail === 'string' ? detail : Array.isArray(detail) ? detail.map(x => x.msg).join('；') : `请求失败（HTTP ${response.status}）`);error.status=response.status;throw error;}return data;
 } catch(error) {if (error.name === 'AbortError') throw new Error(method === 'GET' ? '读取已取消或超时，请重试。' : '请求已停止等待或超时。写入可能已完成，请先核对账本；相同草稿重试会去重。');if (error instanceof TypeError) throw new Error('无法连接服务，请确认后端已启动，并在设置中检查服务地址。');throw error;
 } finally {clearTimeout(timer);signal?.removeEventListener('abort', abort);}
}
export const book = (path, options) => request('book', path, options);
export const trader = (path, options) => request('trader', path, options);
export async function allBills(params) {const rows=[];let offset=0;for (;;) {const page = await book('/bills?' + new URLSearchParams({...params, limit:500, offset}));rows.push(...page);if(page.length < 500) return rows;offset += page.length;if(offset >= 100000)throw new Error('当前区间账单过多，请缩小日期范围。');}}
