import {createFeatures} from './features.js';
import {createNavigation,parseRoute,routes,primaryTabs} from './navigation.js';
import {createJourney} from './journey.js';
import {createInvestment} from './investment.js';
import {createResearch} from './research.js';
import {finance} from './finance-api.js';
import {createStatements} from './statements.js';
import {createGoals} from './goals.js';
import {createImprovement} from './improvement.js';
import {storage, book, trader, baseURL, saveConnections, resetConnections, allBills} from './api.js';
const $ = (s, root=document) => root.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={visualization:'M4 3v18h17 M8 16v-5 M13 16V6 M18 16v-8',home:'M3 7h18v14H3z M3 7l3-4h12l3 4 M15 11h6v6h-6z M17 14h1',ledger:'M6 3h12v18l-3-2-3 2-3-2-3 2z M9 7h6 M9 11h6 M9 15h4',assistant:'M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',investment:'M3 17l6-6 4 4 8-10 M15 5h6v6',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',back:'M15 5l-7 7 7 7',next:'M9 5l7 7-7 7',down:'M6 9l6 6 6-6',add:'M12 5v14 M5 12h14',eye:'M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12 M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',refresh:'M20 7a9 9 0 1 0 1 8 M20 3v5h-5',close:'M6 6l12 12 M18 6L6 18',send:'M12 19V5 M5 12l7-7 7 7',search:'M10 17a7 7 0 1 1 0-14 7 7 0 0 1 0 14 M15 15l6 6',filter:'M4 6h16 M7 12h10 M10 18h4',food:'M4 3v6c0 3 6 3 6 0V3 M7 3v18 M18 3c-3 4-3 8 0 9h2 M20 3v18',transport:'M5 3h14v14H5z M8 17l-2 4 M16 17l2 4 M5 10h14 M8 14h1 M15 14h1',shopping:'M4 7h16l-1 14H5z M8 8V6a4 4 0 0 1 8 0v2',fun:'M4 6h16v15H4z M4 6V3h16v3 M7 3l3 3 M13 3l3 3',house:'M3 10l9-7 9 7 M5 9v12h14V9 M10 21v-8h4v8',other:'M5 12h.1 M12 12h.1 M19 12h.1',calendar:'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16',copy:'M9 9h12v12H9z M15 5V3H3v12h2',upload:'M12 16V3 M7 8l5-5 5 5 M4 15v6h16v-6',check:'M4 12l5 5L20 6',shield:'M12 2l8 4v6c0 5-8 10-8 10S4 17 4 12V6z',star:'M12 3l3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',delete:'M3 6h18 M8 6V3h8v3 M5 6l1 15h12l1-15 M10 10v7 M14 10v7'};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.other}"/></svg>`;
const expenseCategories=['餐饮','出行','购物','生活缴费','娱乐','住房','医疗健康','教育学习','保险','人情往来','旅行','其他'];const incomeCategories=['工资','奖金','副业','理财收益','退款','其他收入'];const categories=[...expenseCategories,...incomeCategories];const entryCategories=()=>draft.type==='income'?incomeCategories:expenseCategories;const categoryIcons={'餐饮':'food','出行':'transport','购物':'shopping','生活缴费':'house','娱乐':'fun','其他':'other'};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const dateISO = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const prefs=storage.get('QINGCAI_PREFS',{mask:false,reduceTransparency:false,reduceMotion:false,period:'month'});
const state={route:'home',month:today().slice(0,7),period:prefs.period||'month',filter:{category:'',type:'',q:''},ledgerRange:null,bills:[],mode:'book',insightTab:'收支',investmentTab:'自选',stockTab:'日报',stockDays:10,stockCode:'600036',stockName:'招商银行',chats:storage.get('QINGCAI_CHATS',{book:[],trader:[]}),reports:{},quotes:{},watchlist:[],favorites:storage.get('QINGCAI_FAVORITES',[]),chatBusy:false,chatDraft:'',epoch:0};
if(!Array.isArray(state.chats.finance))state.chats.finance=[];
let ledgerContextPromise;
async function ensureLedgerContext(){
 if(!ledgerContextPromise)ledgerContextPromise=book('/health').then(info=>{
  state.ledgerInfo=info;
  if(!state.monthInitialized){state.month=info.date_range?.end?.slice(0,7)||today().slice(0,7);state.monthInitialized=true;}
 }).catch(error=>{ledgerContextPromise=null;throw error;});
 return ledgerContextPromise;
}
const filterCategories=()=>[...new Set([...categories,...(state.ledgerInfo?.categories||[])])];
const uid=()=>globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`;
let draft=storage.get('QINGCAI_DRAFT',null) || freshDraft();
// The visible entry form belongs to this exact draft object. A parse, discard or
// successful save replaces it, so old DOM values must not overwrite the new draft.
let renderedEntryDraft;
function freshDraft(){return {event_date:today(),amount:'',category:'餐饮',type:'expense',description:'',currency:'CNY',payment:'',client_request_id:uid()};}
function persistPrefs(){storage.set('QINGCAI_PREFS',prefs);applyPrefs();}
function applyPrefs(){document.documentElement.dataset.reduceTransparency=String(prefs.reduceTransparency);document.documentElement.dataset.reduceMotion=String(prefs.reduceMotion);}
applyPrefs();
function money(value,currency='CNY'){if(prefs.mask)return '••••';const n=Number(value);if(!Number.isFinite(n))return '—';try{return new Intl.NumberFormat('zh-CN',{style:'currency',currency,minimumFractionDigits:2}).format(n);}catch{return `${currency} ${n.toFixed(2)}`;}}
function number(value,digits=2){return prefs.mask?'••••':Number.isFinite(Number(value))?Number(value).toLocaleString('zh-CN',{maximumFractionDigits:digits,minimumFractionDigits:digits}):'—';}
function pct(value){return prefs.mask?'••••':`${Number(value)>=0?'+':''}${Number(value).toFixed(2)}%`;}
function range(period='month'){const [y,m]=state.month.split('-').map(Number);let start=new Date(y,m-1,1),end=new Date(y,m,0);if(period==='year'){start=new Date(y,0,1);end=new Date(y,11,31);}if(period==='week'){const ref=state.month===today().slice(0,7)?new Date(today()+'T12:00:00'):new Date(y,m-1,1);const weekday=(ref.getDay()+6)%7;start=new Date(ref);start.setDate(ref.getDate()-weekday);end=new Date(start);end.setDate(start.getDate()+6);}if(dateISO(start)<=today()&&dateISO(end)>today())end=new Date(today()+'T12:00:00');return {start_date:dateISO(start),end_date:dateISO(end)};}
const rangeLabel = p => {const r=range(p);return `${r.start_date} — ${r.end_date}`;};
const btn=(label,action,cls='',extra='')=>`<button class="btn ${cls}" data-action="${action}" ${extra}>${label}</button>`;
const ib=(name,label,action,extra='')=>`<button class="icon-button" aria-label="${label}" title="${label}" data-action="${action}" ${extra}>${icon(name)}</button>`;
const card=(content,cls='')=>`<section class="surface-card ${cls}">${content}</section>`;
const loading=()=>`<div class="loading" role="status"><span class="spinner"></span>正在读取</div>`;
const empty=(text,action='')=>`<div class="empty">${icon('ledger')}<p>${esc(text)}</p>${action}</div>`;
const errorHTML=error=>`<div class="error" role="alert">${esc(error.message || error)}<div class="mt">${btn('重试','refresh','small')}</div></div>`;
function segmented(values,selected,action){return `<div class="segmented glass" role="tablist">${values.map(x=>`<button role="tab" aria-selected="${x===selected}" data-action="${action}" data-value="${esc(x)}">${esc(x)}</button>`).join('')}</div>`;}
function toast(text){const el=$('#toast');el.textContent=text;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',3300);}
function modal(title,body){const dialog=$('#sheet');$('#sheet-content').innerHTML=`<div class="sheet-head"><h2>${esc(title)}</h2>${ib('close','关闭','close-sheet')}</div>${body}`;if(!dialog.open)dialog.showModal();}
function confirmSheet(title,text,action,extra=''){modal(title,`<p class="dialog-message">${esc(text)}</p><div class="actions">${btn('取消','close-sheet')}${btn('确认',action,'primary',extra)}</div>`);}
function closeSheet(){$('#sheet').close();}
const pageDrafts=new Map();
const retainedForms='#finance-profile-form,#connections-form,#statement-file-form,#visual-range-form';
function retainPageDraft(){
 syncDraft();
 const form=$('#content')?.querySelector(retainedForms);
 if(!form||form.querySelector('button[type="submit"]:disabled'))return;
 pageDrafts.set(state.route,{form:form.id,fields:[...form.querySelectorAll('input,select,textarea')].map(el=>({id:el.id,name:el.name,type:el.type,value:el.value,checked:el.checked,files:el.type==='file'?el.files:null}))});
}
function restorePageDraft(root){
 const saved=pageDrafts.get(state.route);if(!saved)return;
 const form=root.querySelector('#'+saved.form);if(!form)return;
 for(const item of saved.fields){const el=item.id?form.querySelector('#'+item.id):[...form.querySelectorAll('input')].find(el=>el.name===item.name&&el.value===item.value);if(!el)continue;if(item.type==='file'){if(item.files?.length)el.files=item.files;}else if(['radio','checkbox'].includes(item.type))el.checked=item.checked;else el.value=item.value;}
}
const navigation=createNavigation({window,onChange:()=>{closeSheet();render();},beforeLeave:retainPageDraft});
function go(route,options){navigation.go(route,options);}
function ask(text,mode='book',context=null){state.mode=mode;state.chatDraft=text;state.chatContext=context;state.chatLedgerRange=mode==='book'?{...(state.route==='visualization'?state.visualReportRange:state.route==='insights'?(state.insightRange||range(state.period)):state.route==='ledger'?(state.ledgerRange||range()):range())}:null;go('assistant');}
function header(title){const back=navigation.backTarget;const backTitle=back?routes[parseRoute(back).route].title:'';return `<header class="topbar"><div class="topbar-inner"><div class="row topbar-title">${back?ib('back',esc('返回'+backTitle),'back'):''}<h1>${esc(title)}</h1>${state.ledgerInfo?.ledger_scope==='personal'?'<span class="tag">个人账本</span>':''}</div><div class="row topbar-actions">${state.route==='assistant'?ib('refresh','新对话','clear-chat'):state.route==='settings'?'':ib('refresh','刷新','refresh')}${state.route!=='settings'?ib('settings','设置','settings'):''}</div></div></header>`;}
function nav(){return `<nav class="tab-bar glass" aria-label="主导航">${primaryTabs.map(key=>`<a href="#/${key}" data-nav-tab="${key}" ${navigation.activeTab===key?'aria-current="page"':''}>${icon(key)}<span>${routes[key].title}</span></a>`).join('')}</nav>`;}
function monthPicker(){if(state.route==='ledger'&&state.ledgerRange)return `<div class="row between"><div class="range-caption"><strong>${esc(state.ledgerRange.start_date)}</strong><span>至 ${esc(state.ledgerRange.end_date)}</span></div><div class="row">${ib('calendar','返回所选月份','clear-ledger-range')}${ib('filter','筛选账单','filter')}</div>`;return `<div class="row between"><label class="pill glass month-choice" aria-label="月份"><span>${esc(state.month.replace('-','年'))}月</span>${icon('calendar')}<input class="time-input" type="month" id="month-picker" value="${state.month}" aria-label="选择月份"></label><div class="row">${ib('eye',prefs.mask?'显示金额':'隐藏金额','mask')}${state.route==='ledger'?ib('filter','筛选账单','filter'):btn('财务分析','insights','small glass')}</div></div>`;}
function overview(report){return card(`<div class="row between"><span class="muted">区间结余</span><span class="tag">CNY</span></div><span class="hero-amount money">${money(report.net.current)}</span><div class="metrics"><div class="metric"><small><i class="dot"></i>收入</small><strong class="money">${money(report.summary.income_total)}</strong></div><div class="metric"><small><i class="dot dark"></i>支出</small><strong class="money">${money(report.summary.expense_total)}</strong></div></div>`);}
function chart(values,labels,second=null,title='数据'){if(prefs.mask)return '<div class="chart-hidden">金额已隐藏</div>';if(!values.length)return empty('暂无趋势数据');const nums=values.map(Number),all=second?[...nums,...second.map(Number)]:nums;const rawHigh=Math.max(...all),rawLow=Math.min(...all);const padding=Math.max((rawHigh-rawLow)*.12,Math.abs(rawHigh)*.002,.001);const high=second?Math.max(rawHigh,0):rawHigh+padding,low=second?Math.min(rawLow,0):rawLow-padding;const diff=high-low||1;const x=i=>10+(i*300/Math.max(1,nums.length-1)),y=n=>120-((n-low)/diff)*103;const points=nums.map((n,i)=>`${x(i)},${y(n)}`).join(' ');const secondary=second?`<polyline points="${second.map((n,i)=>`${x(i)},${y(n)}`).join(' ')}" fill="none" stroke="#86a396" stroke-width="2"/>`:'';
 return `<div><svg class="chart" viewBox="0 0 320 145" role="img" aria-label="${esc(title)}"><path d="M10 120H310 M10 65H310" stroke="#e7ecf2" stroke-dasharray="3 4"/>${second?'':`<text x="10" y="10" fill="#788698" font-size="9">${number(rawHigh,3)}</text><text x="10" y="142" fill="#788698" font-size="9">${number(rawLow,3)}</text>`}<polygon points="10,130 ${points} ${x(nums.length-1)},130" fill="#1d4ed80c"/>${secondary}<polyline points="${points}" fill="none" stroke="#1d4ed8" stroke-width="2.3" stroke-linejoin="round"/>${nums.map((n,i)=>`<circle class="chart-point" tabindex="0" role="button" aria-label="${esc(labels[i])}：${esc(number(n))}${second?`；收入 ${esc(number(second[i]))}`:''}" data-action="chart-point" data-value="${esc(labels[i])}：${esc(number(n))}${second?`；收入 ${esc(number(second[i]))}`:''}" cx="${x(i)}" cy="${y(n)}" r="${nums.length>15?3:4}" fill="white" stroke="#1d4ed8" stroke-width="1.5"><title>${esc(labels[i])}：${esc(number(n))}</title></circle>`).join('')}</svg><div class="chart-labels"><span>${esc(labels[0])}</span><span>${esc(labels[Math.floor(labels.length/2)])}</span><span>${esc(labels.at(-1))}</span></div><div class="chart-value" aria-live="polite"></div></div>`;
}
function trend(report){return card(`<div class="row between"><h2>收支趋势</h2><div class="legend"><span><b></b>支出</span><span><b class="green"></b>收入</span></div></div>${chart(report.bars.expense,report.bars.labels,report.bars.income,'区间收支趋势')}`);}
function billRows(rows){return rows.map(b=>`<button class="bill-row" data-action="bill" data-id="${b.id}"><span class="bill-icon">${icon(categoryIcons[b.category]||'other')}</span><span class="grow"><strong class="truncate">${esc(b.description)}</strong><small>${esc(b.event_date)} · ${esc(b.category)}${['internal_transfer','principal'].includes(b.metadata?.movement)?' · 划转':''}</small></span><span class="right"><span class="amount money ${b.type==='income'?'good':''}">${b.type==='income'?'+':'−'}${money(b.amount,b.currency)}</span><small>${esc(b.metadata?.payment_method || (b.source==='manual'?'手动录入':b.source||''))}</small></span></button>`).join('');}
function billModal(id){const b=state.bills.find(x=>x.id===Number(id));if(!b)return;modal('账单详情',`<p class="hero-amount center money">${b.type==='income'?'+':'−'}${money(b.amount,b.currency)}</p><div class="col"><h3>${esc(b.description)}</h3><p class="muted">${esc(b.event_date)} · ${esc(b.category)} · ${b.metadata?.movement==='internal_transfer'?'内部划转':b.metadata?.movement==='principal'?'本金划转':b.type==='income'?'收入':'支出'}</p><p class="muted">${esc(b.metadata?.payment_method||'未填写支付方式')}</p></div><div class="actions">${btn('编辑账单','edit-bill','primary',`data-id="${b.id}"`)}${btn('问助手','ask-bill','',`data-id="${b.id}"`)}${btn('删除账单','delete-prompt','danger',`data-id="${b.id}"`)}</div>`);}
async function render(){
 retainPageDraft();
 const {route,query}=parseRoute(location.hash);state.route=route;
 if(route==='stock'){const params=new URLSearchParams(query);state.stockCode=params.get('code')||state.stockCode;state.stockName=params.get('name')||state.stockName;}
 const token=++state.epoch,scrollY=navigation.current.scrollY,title=route==='stock'?state.stockName:routes[route].title;
 const app=$('#app');app.dataset.route=route;
 app.innerHTML=header(title)+`<main id="content" class="page-content ${route}-page ${route==='entry'||route==='settings'?'entry-content':''} ${route==='assistant'?'chat-page':''}">${loading()}</main>`+(!['entry','settings'].includes(route)?nav():'');
 const root=$('#content');
 const paint=html=>{if(token===state.epoch){root.innerHTML=html;restorePageDraft(root);}};
 try{
  if(['home','ledger','insights','visualization','investment','entry','assistant'].includes(route))await ensureLedgerContext();
  if(token!==state.epoch)return;
  document.querySelector('.topbar').outerHTML=header(title);
  await ({home:homePage,ledger:ledgerPage,entry:entryPage,assistant:assistantPage,stock:stockPage,settings:settingsPage,...features.pages,...journey.pages,...investment.pages,...research.pages,...statements.pages,...improvement.pages}[route])(paint);
 }catch(error){paint(errorHTML(error));}
 finally{if(token===state.epoch)requestAnimationFrame(()=>{if(token===state.epoch){window.scrollTo(0,scrollY);navigation.restored();}});}
}
async function homePage(paint){paint(monthPicker()+loading());const params=range();const [report,rows,plan]=await Promise.all([book('/reports/aggregate?'+new URLSearchParams(params)),book('/bills?'+new URLSearchParams({...params,limit:5})),investment.homeBlock()]);state.bills=rows;paint(monthPicker()+overview(report.custom)+`<div class="actions">${btn(icon('add')+'记一笔','entry','primary')}${btn(icon('assistant')+'问助手','ask','glass')}</div>`+plan+trend(report.custom)+card(`<div class="row between"><h2>最近账单</h2>${btn('全部 '+icon('next'),'ledger','small')}</div>${rows.length?billRows(rows):empty('这个月还没有账单',btn('开始记账','entry','small'))}`));}
async function ledgerPage(paint){paint(monthPicker()+loading());const params={...(state.ledgerRange||range()),...(state.filter.category?{category:state.filter.category}:{}),...(state.filter.type?{type:state.filter.type}:{})};const [report,rows]=await Promise.all([book('/reports/aggregate?'+new URLSearchParams(state.ledgerRange||range())),allBills(params)]);state.bills=rows;paint(monthPicker()+overview(report.custom)+btn('资金规划 '+icon('next'),'investment','glass')+`<div class="row"><input id="bill-search" class="field grow" type="search" placeholder="搜索描述、类别或支付方式" value="${esc(state.filter.q)}" aria-label="搜索账单">${ib('upload','导入流水','statement-import')}${ib('add','新增账单','entry')}</div><div class="row between"><small>${esc(state.ledgerRange?state.ledgerRange.start_date+' — '+state.ledgerRange.end_date:'月份总览')} · 筛选：${esc(state.filter.category||'全部分类')} / ${state.filter.type==='income'?'收入':state.filter.type==='expense'?'支出':'全部收支'}</small>${btn('重置','reset-filter','small')}</div><div id="ledger-filter-summary" aria-live="polite"></div><div id="bill-list"></div>`);renderBillList();}
function renderBillList(){const el=$('#bill-list');if(!el)return;const q=state.filter.q.trim().toLowerCase();const rows=state.bills.filter(b=>`${b.description} ${b.category} ${b.metadata?.payment_method||''}`.toLowerCase().includes(q));const days=[...new Set(rows.map(b=>b.event_date))];const sum=type=>rows.filter(b=>b.type===type&&!['principal','internal_transfer'].includes(b.metadata?.movement)).reduce((n,b)=>n+Math.round(Number(b.amount)*100),0)/100;$('#ledger-filter-summary').innerHTML=card(`<div class="row between"><h3>筛选结果</h3><span>${rows.length} 笔</span></div><div class="finance-metrics"><div><span>收入</span><strong>${money(sum('income'))}</strong></div><div><span>支出</span><strong>${money(sum('expense'))}</strong></div></div>`);el.innerHTML=rows.length?days.map(day=>`<div class="row between mb"><h3>${esc(day)}</h3><small>${rows.filter(x=>x.event_date===day).length} 笔</small></div>${card(billRows(rows.filter(x=>x.event_date===day)),'list-card mb')}`).join(''):card(empty('没有找到符合条件的账单',btn('记一笔','entry','small')));}
function entryPage(paint){renderedEntryDraft=draft;paint(`<form id="entry-form"><div class="center mb"><small>金额 · 人民币 CNY</small><label class="row"><span class="muted">¥</span><input id="entry-amount" class="amount-input" name="amount" type="number" inputmode="decimal" step="0.01" min="0.01" max="999999999" required placeholder="0.00" value="${esc(draft.amount)}" aria-label="账单金额"></label></div>${segmented(['支出','收入'],draft.type==='income'?'收入':'支出','entry-type')}<div class="surface-card mt"><h2 class="mb">分类</h2><div class="category-grid">${entryCategories().map(c=>`<button type="button" class="${draft.category===c?'selected':''}" data-action="entry-category" data-value="${c}">${icon(categoryIcons[c])}${c}</button>`).join('')}</div></div><div class="surface-card mt"><div class="form-row"><label class="field-label" for="entry-date">日期</label><input id="entry-date" class="field" type="date" name="event_date" value="${esc(draft.event_date)}" required></div><div class="form-row"><label class="field-label" for="entry-description">描述 / 备注</label><input id="entry-description" class="field" name="description" maxlength="512" placeholder="如：朋友聚餐" value="${esc(draft.description)}" required></div><div><label class="field-label" for="entry-payment">支付方式（可选）</label><select id="entry-payment" class="field" name="payment">${['','微信支付','支付宝','银行卡','信用卡','现金','其他'].map(v=>`<option ${draft.payment===v?'selected':''} value="${v}">${v||'未填写'}</option>`).join('')}</select></div></div><div class="actions mt">${btn(icon('assistant')+'文字解析','parse-entry','small','type="button"')}${state.ledgerInfo?.capabilities?.ocr?btn(icon('upload')+'识别票据','ocr-entry','small','type="button"'):''}</div><div id="entry-error" class="mt"></div><button id="save-entry" class="btn primary mt" style="width:100%" type="submit">保存账单</button><div class="center mt">${btn('丢弃草稿','discard-draft','small','type="button"')}</div></form>`);$('#entry-form')?.querySelectorAll('.segmented button').forEach(b=>b.type='button');}
function syncDraft(){const form=$('#entry-form');if(!form||renderedEntryDraft!==draft)return;for(const [k,v] of new FormData(form))draft[k]=v;storage.set('QINGCAI_DRAFT',draft);}
function parseObject(reply){const match=String(reply).match(/\{[\s\S]*\}/);if(!match)throw new Error('未得到有效的账单 JSON，请改用手动录入。');return JSON.parse(match[0]);}
function applyParsed(p){if(p.needs_clarification)throw new Error(p.reason||'请补充账单信息');const amount=Number(p.amount??p['金额']);const date=p.event_date??p['日期'];if(!(amount>0)||!/^\d{4}-\d{2}-\d{2}$/.test(date||''))throw new Error('识别结果缺少有效金额或日期，请手动填写。');const currency=p.currency||p['币种']||'CNY';if(currency!=='CNY')throw new Error('当前记账页使用人民币，识别到其他币种，请确认金额后手动录入。');draft={...draft,client_request_id:uid(),amount:amount.toFixed(2),event_date:date,category:categories.includes(p.category??p['类别'])?(p.category??p['类别']):'其他',description:String(p.description??p['描述']??p.merchant??p['商户']??''),type:p.type==='income'?'income':'expense',payment:p.payment_method||''};storage.set('QINGCAI_DRAFT',draft);closeSheet();go('entry');toast('已填入草稿，请核对后保存');}
async function saveEntry(){syncDraft();const button=$('#save-entry');if(button.disabled)return;button.disabled=true;button.textContent='正在保存';const {payment,client_request_id,pending,...data}=draft;draft.pending=true;storage.set('QINGCAI_DRAFT',draft);try{const result=await book('/bills',{method:'POST',body:{...data,amount:Number(data.amount),source:'manual',metadata:{payment_method:payment,client_request_id}},timeout:20000});state.month=result.event_date.slice(0,7);state.monthInitialized=true;state.ledgerRange=null;ledgerContextPromise=null;draft=freshDraft();storage.set('QINGCAI_DRAFT',draft);go('ledger');toast(`已保存，账单 #${result.id}`);}catch(error){$('#entry-error').innerHTML=`<div class="error" role="alert">${esc(error.message)}</div>`;button.disabled=false;button.textContent='重试保存';}}
function habitText(b){const flags=b.risk_flags||[];return flags.length?flags.map(x=>typeof x==='string'?x:`${x.category}：${x.message}（月均 ${money(x.avg)}）`).join('\n\n'):'当前数据没有产生额外行为提示。继续记账后，可观察更长时间的变化。';}
function categoryDistribution(report){const total=report.summary.expense_total;return report.pie.length?report.pie.map(c=>`<button class="category-row" data-action="category-ledger" data-value="${esc(c.name)}"><span class="row between"><span>${esc(c.name)}</span><span class="money">${money(c.value)} <small>${prefs.mask?'':(c.value/total*100).toFixed(1)+'%'}</small></span></span>${prefs.mask?'':`<span class="progress-bar"><span style="width:${Math.min(100,c.value/total*100)}%"></span></span>`}</button>`).join(''):empty('本期暂无支出');}
function assistantPage(paint){paint(segmented(['记账','规划','投研'],state.mode==='book'?'记账':state.mode==='finance'?'规划':'投研','chat-mode')+(state.mode==='finance'?journey.chatTools():features.chatTools())+`<div class="chips">${(state.mode==='book'?['这个月还剩多少钱？','帮我看看最近消费','生成财务建议']:state.mode==='finance'?['我的月结余怎样安排？','目标每月需要预留多少？','先留多少应急金？']:['解读当前组合风险','如何阅读个股日报？','查看自选股']).map(x=>`<button data-action="suggestion" data-value="${x}">${x}</button>`).join('')}</div><div id="chat-messages" class="chat-messages"></div><form id="chat-form" class="composer glass">${ib('add','快捷输入与操作','chat-add','type="button"')}<textarea id="chat-input" rows="1" placeholder="${state.mode==='book'?'向记账助手提问…':state.mode==='finance'?'聊聊计划，或告诉我想做的操作…':'向投研助手提问…'}" aria-label="消息" ${state.chatBusy?'disabled':''}>${esc(state.chatDraft)}</textarea>${state.chatBusy?ib('close','停止等待','stop-chat','type="button"'):ib('send','发送消息','send','type="submit"')}</form>`);renderMessages();}
function renderMessages(){const root=$('#chat-messages');if(!root)return;const messages=state.chats[state.mode]||[];root.innerHTML=messages.length?messages.map((m,i)=>`<article class="chat-message ${m.role==='user'?'user':''}"><div class="bubble">${prefs.mask?'对话内容已隐藏':m.role==='assistant'?features.replyHTML(m.content):esc(m.content)}</div>${state.mode==='finance'&&m.role==='assistant'&&!m.failed?journey.chatDraftButton(m,i):''}<small>${m.role==='user'?'你':'助手'} · ${esc(m.time||'')}${m.failed?' · 未完成':''}</small>${m.role==='assistant'&&!m.failed?`<button class="pill" data-action="copy-message" data-index="${i}">${icon('copy')}复制</button>`:''}</article>`).join(''):empty(state.mode==='book'?'开始聊聊你的收支':'开始聊聊你的投资');if(state.chatBusy)root.innerHTML+=loading();}
async function sendChat(){const text=$('#chat-input').value.trim();if(!text||state.chatBusy)return;const mode=state.mode;const selectedContext=state.chatContext;state.chatDraft='';state.chatBusy=true;state.chatController=new AbortController();const time=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});state.chats[mode].push({role:'user',content:text,time});storage.set('QINGCAI_CHATS',state.chats);render();try{const history=state.chats[mode].filter(x=>!x.failed).slice(-20).map(({role,content})=>({role,content}));let context='请使用简体中文回答。只提供可核对的结论，不得声称已执行转账、交易或自动入账。';if(mode==='book'&&selectedContext)context+='用户正在查看的区间数据如下，优先按此区间回答，不能混入其他月份：'+JSON.stringify(selectedContext);if(mode==='trader'){const portfolio=await trader('/trader/portfolio');context+='以下是历史组合快照，并非实时行情：'+JSON.stringify(portfolio);}let financeReply;if(mode==='finance'){financeReply=await finance('/assistant',{method:'POST',body:{messages:history.slice(-12)},timeout:180000,signal:state.chatController.signal});}const reply=financeReply || await (mode==='book'?book:trader)('/chat',{method:'POST',body:{messages:history,system_prompt:context,include_bill_context:mode==='book',...(mode==='book'?{ledger_range:chatRange(text)}:{}),max_new_tokens:1600},timeout:180000,signal:state.chatController.signal});state.chats[mode].push({role:'assistant',content:reply.reply,plan_next:financeReply?.plan_next||null,action_draft:financeReply?.draft?{...financeReply.draft,feedback_ref:financeReply.feedback_ref,request_id:uid()}:null,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});}catch(error){state.chats[mode].push({role:'assistant',content:state.chatController.signal.aborted?'已停止等待回复。':error.message,time:'',failed:true});}finally{state.chatBusy=false;storage.set('QINGCAI_CHATS',state.chats);if(state.route==='assistant'){await render();$('#chat-messages')?.lastElementChild?.scrollIntoView({block:'center'});}}}

function chatRange(text){
 const selected=state.chatLedgerRange||range();
 const explicit=text.match(/(?:(20\d{2})年)?(1[0-2]|0?[1-9])月/);
 if(explicit){const year=explicit[1]||selected.start_date.slice(0,4),month=Number(explicit[2]);return {start_date:`${year}-${String(month).padStart(2,'0')}-01`,end_date:dateISO(new Date(Number(year),month,0))};}
 return selected;
}
function editBill(id){
 const b=state.bills.find(x=>x.id===Number(id));if(!b)return;
 const opts=type=>(type==='income'?incomeCategories:expenseCategories).map(c=>`<option ${b.category===c?'selected':''}>${esc(c)}</option>`).join('');
 modal('编辑账单',`<form id="bill-edit-form" data-id="${b.id}" data-version="${esc(b.version)}"><label class="field-label" for="edit-amount">金额（元）</label><input class="field" id="edit-amount" name="amount" type="number" min="0.01" step="0.01" max="999999999" required value="${b.amount}"><label class="field-label" for="edit-type">收支</label><select class="field" id="edit-type" name="type"><option value="expense" ${b.type==='expense'?'selected':''}>支出</option><option value="income" ${b.type==='income'?'selected':''}>收入</option></select><label class="field-label" for="edit-category">分类</label><select class="field" id="edit-category" name="category">${opts(b.type)}</select><label class="field-label" for="edit-date">日期</label><input class="field" id="edit-date" name="event_date" type="date" required value="${esc(b.event_date)}"><label class="field-label" for="edit-description">描述</label><input class="field" id="edit-description" name="description" maxlength="512" required value="${esc(b.description)}"><label class="field-label" for="edit-payment">支付方式</label><input class="field" id="edit-payment" name="payment_method" maxlength="40" value="${esc(b.metadata?.payment_method||'')}"><p class="field-feedback" role="alert"></p><div class="actions">${btn('取消','close-sheet','','type="button"')}<button type="submit" class="btn primary">保存修改</button></div></form>`);
}
document.addEventListener('change',e=>{if(e.target.id==='edit-type')$('#edit-category').innerHTML=(e.target.value==='income'?incomeCategories:expenseCategories).map(c=>`<option>${esc(c)}</option>`).join('');});
document.addEventListener('submit',async e=>{
 const form=e.target;if(form.id!=='bill-edit-form')return;e.preventDefault();
 const button=form.querySelector('[type="submit"]');if(button.disabled)return;button.disabled=true;
 try{const data=Object.fromEntries(new FormData(form));const result=await book('/bills/'+form.dataset.id,{method:'PUT',body:{...data,amount:Number(data.amount),currency:'CNY',expected_version:form.dataset.version}});ledgerContextPromise=null;closeSheet();await render();toast('账单已更新');}
 catch(error){form.querySelector('[role="alert"]').textContent=error.message;}
 finally{if(button.isConnected)button.disabled=false;}
});

function stockLink(code,name){go('stock?'+new URLSearchParams({code,name}));}
function reportSections(text){const chunks=String(text).split(/\n(?=(?:#{1,4}\s|\*\*))/).filter(x=>x.trim());return chunks.map((chunk,i)=>{const lines=chunk.trim().split('\n');let title=lines[0].replace(/^#+\s*|\*\*/g,'').trim();if(title.length>40||lines.length<2){title=`研究内容${chunks.length>1?' '+(i+1):''}`;}else lines.shift();const body=lines.join('\n');return `<details class="report-section"><summary>${esc(title)}</summary><div class="report-text">${esc(prefs.mask?'内容已隐藏':body)}</div></details><p class="report-preview">${esc(prefs.mask?'内容已隐藏':body)}</p>`;}).join('');}
async function stockPage(paint){paint(loading());if(!state.watchlist.length)state.watchlist=await trader('/trader/watchlist');const supported=state.watchlist.some(x=>x.code===state.stockCode);if(!supported){const p=state.portfolio||await trader('/trader/portfolio');const h=p.holdings.find(x=>x.code===state.stockCode);paint(card(`<h2>${esc(state.stockName)}</h2><p class="period-stamp">${esc(state.stockCode)}</p>${h?`<span class="hero-amount money">${money(h.market_value,p.summary.base_currency)}</span><p>持仓收益 ${pct(h.pnl_pct)}</p>`:''}<div class="empty">暂无行情或研报</div><div class="mt">${btn('查看 A10 自选','watchlist','primary')}</div>`));return;}
 const [rows,quality]=await Promise.all([trader(`/trader/stock/${encodeURIComponent(state.stockCode)}/kline?days=${state.stockDays}`),trader(`/trader/stock/${encodeURIComponent(state.stockCode)}/quality`)]);state.quotes[state.stockCode]=rows;const last=rows.at(-1),prev=rows.at(-2);const change=last&&prev?Number(last.close)-Number(prev.close):null;const changePct=change!==null&&Number(prev.close)!==0?change/Number(prev.close)*100:null;let content='';if(state.stockTab==='资讯'){const news=await trader(`/trader/stock/${state.stockCode}/news`);state.news=[...(news.news||[]),...(news.reports||[])];content=card(`<h2>历史资讯与研报</h2>${state.news.length?state.news.map((n,i)=>`<button class="news-row" data-action="news" data-index="${i}"><span>${esc(n['新闻标题']||n['报告名称']||n.title||'资讯')}</span><small>${esc(n['发布时间']||n['发布日期']||n['日期']||'')} · ${esc(n['文章来源']||n['机构']||n.source||'')}</small></button>`).join(''):empty('没有资讯记录')}`);}else content=card(`<div class="row between mb"><h2>研究日报</h2>${btn(state.reports[state.stockCode]?'重新生成':'生成研究','stock-report','small glass')}</div>${state.reports[state.stockCode]?reportSections(state.reports[state.stockCode]):empty('根据这只股票现有的行情与资讯生成研究。')}`);
 paint(`<div class="row between"><span class="muted">${esc(state.stockCode)} · CNY</span>${btn(icon('star')+(state.favorites.includes(state.stockCode)?'已关注':'关注'),'favorite','small glass')}</div>`+card(last?`<small>最近收盘价</small><span class="hero-amount money">${money(last.close)}</span><p class="${change>=0?'good':'bad'}">${change===null?'—':`${change>=0?'+':''}${money(change)} (${pct(changePct)})`}</p><div class="quote-grid"><div><small>开盘</small>${money(last.open)}</div><div><small>最高</small>${money(last.high)}</div><div><small>最低</small>${money(last.low)}</div><div><small>成交量（原始值）</small>${number(last.volume,0)}</div></div>${chart(rows.map(x=>Number(x.close)),rows.map(x=>x.date),null,'历史收盘走势')}<p class="period-stamp">${esc(last.date)}</p>${Number(last.high)<Number(last.low)?'<p class="status mt">原始文件的最高 / 最低价存在不一致，请核对数据源。</p>':''}`:empty(quality.excluded?'行情待核对':'暂无行情'))+(quality.excluded?card(`<details><summary>行情校验 · 已排除 ${quality.excluded} 条</summary><p class="dialog-message">最高价、最低价或价格区间异常。仅使用通过校验的历史记录，原始文件保持不变。</p></details>`):'')+segmented(['10日','30日','90日'],state.stockDays+'日','stock-days')+segmented(['日报','资讯'],state.stockTab,'stock-tab')+content+btn('问投研助手','stock-ask','primary'));
}
function settingsPage(paint){paint(card(`<h2 class="mb">外观与隐私</h2>${[['mask','隐藏金额'],['reduceTransparency','减少透明度'],['reduceMotion','减少动画']].map(([key,label])=>`<label class="setting-row" for="pref-${key}"><span>${label}</span><input class="switch" id="pref-${key}" type="checkbox" data-pref="${key}" ${prefs[key]?'checked':''}></label>`).join('')}`)+card(`<h2 class="mb">数据与显示</h2><label class="setting-row">默认分析范围<select id="default-period" class="time-input">${[['week','周'],['month','月'],['year','年']].map(([v,t])=>`<option value="${v}" ${prefs.period===v?'selected':''}>${t}</option>`).join('')}</select></label><div class="setting-row"><span>记账货币</span><span class="muted">人民币 CNY</span></div><div class="setting-row"><span>数据刷新</span>${btn('立即刷新','refresh-data','small')}</div>`)+card(`<h2>服务状态</h2><div id="service-status"></div><div class="mt">${btn('测试连接','health','small glass')}</div>`)+card(`<details><summary>高级设置</summary><form id="connections-form" class="mt"><label class="field-label" for="book-url">记账服务地址</label><input class="field" type="url" required id="book-url" value="${esc(baseURL('book'))}"><label class="field-label mt" for="trader-url">投研服务地址</label><input class="field" type="url" required id="trader-url" value="${esc(baseURL('trader'))}"><div class="actions"><button type="submit" class="btn primary">保存</button>${btn('恢复默认','reset-connections','','type="button"')}</div><p id="connections-error" class="field-feedback" role="alert"></p></form></details>`)+card(`<div class="setting-row"><span>一起改进助手</span>${btn('查看','improvement-open','small glass')}</div>`)+card(btn('清空本机对话','clear-all-chat','danger'))+``);}
async function busy(button, action){if(button?.disabled)return;const original=button?.innerHTML;if(button){button.disabled=true;button.innerHTML='处理中…';}try{await action();}catch(error){modal('操作未完成',`<div class="error" role="alert">${esc(error.message)}</div>`);}finally{if(button?.isConnected){button.disabled=false;button.innerHTML=original;}}}
async function healthCheck(button){await busy(button,async()=>{const results=await Promise.allSettled([book('/health'),trader('/health')]);const container=$('#service-status');if(container)container.innerHTML=results.map((r,i)=>{const ok=r.status==='fulfilled'&&r.value.status==='ok';const llm=ok?r.value.llm:null;return `<div class="setting-row"><div><span>${i?'投研服务':'记账服务'}</span><small style="display:block">${ok?(llm?.loaded&&llm?.fine_tuned?'新版微调模型已加载':llm?.configured?'模型已配置（调用时验证）':'AI 尚未配置'):esc(r.reason?.message||r.value?.error||'服务不可用')}</small></div><span class="tag ${ok?'success':'warning'}">${ok?'已连接':'未连接'}</span></div>`;}).join('');});}
async function generatedReport(button, stock=false){await busy(button,async()=>{const code=state.stockCode;const result=await trader(stock?`/trader/stock/${encodeURIComponent(code)}/daily_report`:'/trader/analyst/report',{method:'POST',timeout:180000});if(stock){state.reports[code]=result.reply;if(state.route==='stock'&&state.stockCode===code)render();else toast('研究报告已生成');}else modal('组合解读',`${reportSections(result.reply)}`);});}
const featureContext={state,prefs,storage,book,trader,esc,money,number,card,btn,icon,loading,empty,range,monthPicker,overview,chart,segmented,modal,closeSheet,toast,render,go,ask,today,habitText,applyParsed,busy,resetLedgerContext:({keepMonth=false}={})=>{ledgerContextPromise=null;if(!keepMonth)state.monthInitialized=false;state.reports={};}};
const goals=createGoals(featureContext);
featureContext.goalCard=goals.goalCard;
const features=createFeatures(featureContext);
const journey=createJourney(featureContext);
const investment=createInvestment(featureContext);
const research=createResearch(featureContext);
const statements=createStatements(featureContext);
const improvement=createImprovement(featureContext);
const actions={
 'home':()=>go('home'),'ledger':()=>go('ledger'),'entry':()=>go('entry'),'insights':()=>go('insights'),'settings':()=>go('settings'),
 'back':()=>navigation.back(),'refresh':()=>render(),'close-sheet':closeSheet,
 'mask':()=>{prefs.mask=!prefs.mask;persistPrefs();render();},
 'ask':()=>ask(`${range().start_date} 至 ${range().end_date} 的收支情况怎么样？`),
 'clear-ledger-range':()=>{state.ledgerRange=null;render();},
 'edit-bill':b=>editBill(b.dataset.id),
 'bill':b=>billModal(b.dataset.id),
 'ask-bill':b=>{const bill=state.bills.find(x=>x.id===Number(b.dataset.id));closeSheet();if(bill)ask('请分析这笔账单：'+JSON.stringify(bill));},
 'delete-prompt':b=>confirmSheet('删除这笔账单？','删除后，该账单会从账本和统计中移除。','delete-confirm',`data-id="${b.dataset.id}"`),
 'delete-confirm':b=>busy(b,async()=>{await book('/bills/'+Number(b.dataset.id),{method:'DELETE'});ledgerContextPromise=null;closeSheet();await render();toast('账单已删除');}),
 'filter':()=>modal('筛选账单',`<div class="form-row"><label class="field-label" for="filter-category">分类</label><select id="filter-category" class="field">${['',...filterCategories()].map(c=>`<option value="${esc(c)}" ${state.filter.category===c?'selected':''}>${esc(c||'全部分类')}</option>`).join('')}</select></div><label class="field-label" for="filter-type">收支</label><select id="filter-type" class="field"><option value="">全部</option><option value="expense" ${state.filter.type==='expense'?'selected':''}>支出</option><option value="income" ${state.filter.type==='income'?'selected':''}>收入</option></select><div class="actions">${btn('重置','reset-filter')}${btn('应用筛选','apply-filter','primary')}</div>`),
 'apply-filter':()=>{state.filter.category=$('#filter-category').value;state.filter.type=$('#filter-type').value;closeSheet();render();},
 'reset-filter':()=>{state.filter={category:'',type:'',q:''};state.ledgerRange=null;closeSheet();render();},
 'entry-type':b=>{syncDraft();draft.type=b.dataset.value==='收入'?'income':'expense';if(!entryCategories().includes(draft.category))draft.category=entryCategories()[0];storage.set('QINGCAI_DRAFT',draft);render();},
 'entry-category':b=>{syncDraft();draft.category=b.dataset.value;storage.set('QINGCAI_DRAFT',draft);render();},
 'discard-draft':()=>confirmSheet('丢弃草稿？','金额、分类和备注将被清空。','discard-confirm'),
 'discard-confirm':()=>{draft=freshDraft();storage.set('QINGCAI_DRAFT',draft);closeSheet();render();},
 'parse-entry':()=>{syncDraft();modal('文字解析',`<label class="field-label" for="parse-text">描述这笔收支</label><textarea class="field" id="parse-text" placeholder="例如：今天中午用微信吃饭花了 28 元"></textarea><div class="mt">${btn('解析','parse-confirm','primary')}</div>`);},
 'parse-confirm':b=>busy(b,async()=>{const text=$('#parse-text').value.trim();if(!text)throw new Error('请先输入账单描述');const parsed=await book('/bills/parse',{method:'POST',body:{text,reference_date:today()},timeout:180000});applyParsed(parsed);}),
 'ocr-entry':()=>{if(!state.ledgerInfo?.capabilities?.ocr){actions['parse-entry']();return;}syncDraft();modal('识别票据',`<input class="field" id="receipt-file" type="file" accept="image/*" aria-label="选择票据图片"><div class="mt">${btn('开始识别','ocr-confirm','primary')}</div>`);},
 'ocr-confirm':b=>busy(b,async()=>{const file=$('#receipt-file').files[0];if(!file)throw new Error('请先选择图片');if(file.size>10*1024*1024)throw new Error('图片不能超过 10 MB');const form=new FormData();form.append('file',file);const result=await book('/bills/ocr',{method:'POST',body:form,timeout:180000});applyParsed(result.parsed);}),
 'insight-tab':b=>{state.insightTab=b.dataset.value;render();},
 'period':b=>{state.period={'周':'week','月':'month','年':'year'}[b.dataset.value];render();},
 'category-ledger':b=>{state.ledgerRange=range(state.period);state.filter.category=b.dataset.value;state.filter.q='';state.filter.type='expense';go('ledger');},
 'insight-advice':()=>ask('请基于以下真实区间统计给出简短财务建议，不要臆测其他数据：'+JSON.stringify(state.currentReport)),
 'chart-point':b=>{const el=b.closest('.chart-container')?.querySelector('.chart-value')||b.closest('svg').parentElement.querySelector('.chart-value');if(el)el.textContent=b.dataset.value;},
 'chat-mode':b=>{if(state.chatBusy){toast('请先等待回复或停止等待');return;}state.chatDraft=$('#chat-input')?.value||'';state.mode=b.dataset.value==='投研'?'trader':b.dataset.value==='规划'?'finance':'book';state.chatContext=null;state.chatLedgerRange=null;render();},
 'suggestion':b=>{if(b.dataset.value==='查看自选股'){actions.watchlist();return;}const input=$('#chat-input');input.value=b.dataset.value;state.chatDraft=b.dataset.value;state.chatContext=null;input.focus();},
 'send':()=>{},
 'stop-chat':()=>state.chatController?.abort(),
 'copy-message':b=>busy(b,async()=>{const text=state.chats[state.mode][Number(b.dataset.index)]?.content;if(text){await navigator.clipboard.writeText(text);toast('已复制');}}),
 'clear-chat':()=>{if(state.chatBusy){toast('请先停止等待回复');return;}confirmSheet('开始新对话？','将清空本机当前模式的对话记录。','clear-chat-confirm');},
 'clear-chat-confirm':()=>{state.chats[state.mode]=[];storage.set('QINGCAI_CHATS',state.chats);state.chatDraft='';state.chatContext=null;closeSheet();render();},
 'clear-all-chat':()=>{if(state.chatBusy){toast('请先停止等待回复');return;}confirmSheet('清空本机对话？','本机全部对话将被清除，账本不受影响。','clear-all-confirm');},
 'clear-all-confirm':()=>{state.chats={book:[],trader:[],finance:[]};storage.set('QINGCAI_CHATS',state.chats);closeSheet();toast('本机对话已清空');},
 'investment-tab':b=>{state.investmentTab=b.dataset.value;render();},
 'stock':b=>stockLink(b.dataset.code,b.dataset.name),
 'watchlist':()=>{closeSheet();state.investmentTab='自选';go('research');},
 'portfolio-report':b=>generatedReport(b),
 'investment-ask':()=>ask('请解读当前组合的配置与风险。','trader'),
 'stock-tab':b=>{state.stockTab=b.dataset.value;render();},
 'stock-days':b=>{state.stockDays=parseInt(b.dataset.value,10);render();},
 'stock-report':b=>generatedReport(b,true),
 'stock-ask':()=>ask(`请分析 ${state.stockName}（${state.stockCode}）。以下是项目历史行情：${JSON.stringify(state.quotes[state.stockCode]||[])}。请明确数据日期。`,'trader'),
 'favorite':()=>{const code=state.stockCode;state.favorites=state.favorites.includes(code)?state.favorites.filter(x=>x!==code):[...state.favorites,code];storage.set('QINGCAI_FAVORITES',state.favorites);render();},
 'news':b=>{const item=state.news[Number(b.dataset.index)];if(!item)return;const title=item['新闻标题']||item['报告名称']||'资讯详情';const body=item['新闻内容']||item.content||item['摘要']||JSON.stringify(item,null,2);const url=item['新闻链接']||item['报告链接']||item.url;let link='';try{const u=new URL(url);if(['http:','https:'].includes(u.protocol))link=`<a class="btn mt" href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">查看来源</a>`;}catch{}modal(title,`<div class="report-text">${esc(body)}</div>${link}`);},
 'health':healthCheck,
 'reset-connections':()=>{resetConnections();ledgerContextPromise=null;state.monthInitialized=false;state.reports={};render();toast('服务地址已恢复默认');},
 'refresh-data':()=>{state.reports={};state.quotes={};state.watchlist=[];ledgerContextPromise=null;toast('缓存已清除，页面将重新读取数据');},
};
Object.assign(actions,features.actions,journey.actions,investment.actions,research.actions,statements.actions,goals.actions,improvement.actions);
const legacyChatAdd=actions['chat-add'];
actions['chat-add']=b=>state.mode==='finance'?journey.showQuickInputs():legacyChatAdd(b);
document.addEventListener('input',features.onInput);
document.addEventListener('change',features.onChange);
document.addEventListener('submit',features.onSubmit);
document.addEventListener('submit',journey.onSubmit);
document.addEventListener('submit',statements.onSubmit);
document.addEventListener('input',statements.onInput);
document.addEventListener('change',statements.onChange);
document.addEventListener('submit',goals.onSubmit);
document.addEventListener('click',event=>{const tab=event.target.closest('[data-nav-tab]');if(tab&&!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey&&event.button===0){event.preventDefault();go(tab.dataset.navTab,{root:true});return;}const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;if(action!=='send')event.preventDefault();if(['entry','ledger','insights','settings'].includes(action)&&$('#sheet').open)closeSheet();const handler=actions[action];if(handler)Promise.resolve(handler(button)).catch(e=>toast(e.message));});
document.addEventListener('keydown',event=>{const point=event.target.closest('.chart-point');if(point&&['Enter',' '].includes(event.key)){event.preventDefault();actions[point.dataset.action]?.(point);}if(event.target.id==='chat-input'&&event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();sendChat();}});
document.addEventListener('input',event=>{if(event.target.closest(retainedForms))retainPageDraft();if(event.target.closest('#entry-form')){if(draft.pending){draft.client_request_id=uid();draft.pending=false;}syncDraft();}if(event.target.id==='bill-search'){state.filter.q=event.target.value;renderBillList();}if(event.target.id==='chat-input')state.chatDraft=event.target.value;});
document.addEventListener('change',event=>{const el=event.target;if(el.closest(retainedForms))retainPageDraft();if(el.id==='month-picker'&&/^\d{4}-\d{2}$/.test(el.value)){state.month=el.value;state.monthInitialized=true;state.ledgerRange=null;render();}if(el.dataset.pref){prefs[el.dataset.pref]=el.checked;persistPrefs();}if(el.id==='default-period'){prefs.period=el.value;state.period=el.value;persistPrefs();}});
document.addEventListener('submit',async event=>{event.preventDefault();if(event.target.id==='entry-form'){await saveEntry();}if(event.target.id==='chat-form')await sendChat();if(event.target.id==='connections-form'){try{saveConnections($('#book-url').value.trim(),$('#trader-url').value.trim());ledgerContextPromise=null;state.monthInitialized=false;state.reports={};state.watchlist=[];toast('服务地址已保存');}catch(error){$('#connections-error').textContent=error.message;}}});
$('#sheet').addEventListener('click',event=>{if(event.target===$('#sheet')){const r=event.target.getBoundingClientRect();if(event.clientY<r.top||event.clientX<r.left||event.clientX>r.right)closeSheet();}});
document.addEventListener('submit',event=>{if(event.target.matches(retainedForms))pageDrafts.delete(state.route);},true);
window.visualViewport?.addEventListener('resize',()=>{document.body.classList.toggle('keyboard',window.innerHeight-window.visualViewport.height>150);});
render();
